# Adresse IP du tracker
tracker-address = 127.0.0.1

# Numéro de port TCP d'écoute du tracker
tracker-port = 12345

# Intervalle entre deux mises à jour du tracker (ms)
tracker-update-interval-ms = 10000

# Intervalle entre deux échanges périodiques de buffermap entre pairs (ms)
peer-update-interval-ms = 5000

# Fichier de log du peer
log-file = peer.log

# Niveau de verbosité: ERROR, WARN ou INFO
log-level = INFO
